### ISSUE TITLE
LPMultiLineTextField displays scrollbars when text overflows it bounds.

### ISSUE THREAD

**Issue by BlairDuncan** [luddep/LPKit#22] opened 2010-09-03 17:33 UTC
This makes it match the way CPTextField works where if the text overflows the bounds, the overflow is hidden outside of the view area without scrollbars.

Commit is here.
http://github.com/BlairDuncan/LPKit/commit/253de020ae25f0a3f1449e1999ce399c1cf972b0

**Comment by luddep** [comment] 2010-09-03 17:39
This is actually the intended behavior. Since it currently doesn't support cappuccino scrollbars, and you should be able to scroll it - it just uses the native scrollbars.

LPMultilineTextField is not just a CPTextField with "multiline" support, it should be thought of as a textarea equivalent. Which is what it is.

Closing.

**Comment by luddep** [comment] 2010-09-03 17:55
Maybe it should be renamed to LPTextarea.

**Comment by BlairDuncan** [comment] 2010-09-03 19:26
I don't use cocoa but perhaps we could make it optional like NSTextField does through its cell. The cell has a setScrollable and isScrollable.

**Closed as completed** 2010-09-04 00:39 UTC
